const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=r=>fs.readFileSync(path.join(root,r),'utf8');
test('Biblioteca tem escopo global e vínculo contextual',()=>{const h=read('public/index.html');assert.match(h,/id="pdfLibraryScope"/);assert.match(h,/Biblioteca Global/);assert.match(h,/id="modalPdfLink"/);assert.match(h,/pdfLinkMateria/);});
test('PDF global não carrega concurso workspace matéria ou assunto',()=>{const u=read('public/js/pdf/pdf-upload.js');assert.match(u,/documentPayload/);assert.doesNotMatch(u,/documentPayload[\s\S]{0,500}workspace_id/);assert.doesNotMatch(u,/documentPayload[\s\S]{0,500}concurso:/);assert.match(u,/PdfStudyLinks/);assert.match(u,/links\(\)\.create/);});
test('Storage novo independe de workspace',()=>{const c=read('public/js/pdf/pdf-core.js');assert.match(c,/return `\$\{userId\}\/\$\{pdfId\}\/original\.pdf`/);assert.doesNotMatch(c,/workspaceSegment/);});
test('link table permite múltiplos contextos sem duplicar PDF',()=>{const s=read('supabase/migrations/20260818230000_decouple_pdf_from_concurso.sql');assert.match(s,/create table if not exists public\.pdf_document_links/);assert.match(s,/pdf_id uuid not null references public\.pdf_documents\(id\) on delete cascade/);assert.match(s,/concurso text not null/);assert.match(s,/materia text not null/);assert.match(s,/assunto text not null/);assert.match(s,/enable row level security/);});
test('excluir concurso remove somente vínculos',()=>{const l=read('public/js/pdf/pdf-links.js');const c=read('public/js/app-core.js');assert.match(l,/deleteConcursoNow/);assert.match(l,/from\('pdf_document_links'\)\.delete/);assert.doesNotMatch(l,/storage\.from/);assert.match(c,/PdfStudyLinks\?\.handleConcursoDelete/);});
test('excluir PDF global remove arquivo e documento explicitamente',()=>{const l=read('public/js/pdf/pdf-library.js');assert.match(l,/storage\.from\(core\(\)\.BUCKET\)\.remove/);assert.match(l,/from\('pdf_documents'\)\.delete/);});
test('upload PDF tem dropzone explícita e seletor de arquivo acessível',()=>{const h=read('public/index.html');const c=read('public/css/pdf-library.css');assert.match(h,/Selecionar arquivo PDF/);assert.match(h,/role="button"/);assert.match(h,/pdfUploadFile/);assert.match(c,/\.pdf-drop-zone[\s\S]*border:2px dashed/);});
test('modal de upload garante Workspace padrão e permite criar Workspace inline',()=>{const h=read('public/index.html');const u=read('public/js/pdf/pdf-library-ui.js');assert.match(h,/pdf-new-workspace-btn/);assert.match(h,/openWorkspaceModal\('upload'\)/);assert.match(u,/async function openUploadModal/);assert.match(u,/await ensureWorkspace\(\)/);assert.match(u,/Biblioteca Geral/);});

test('upload modal preserva Biblioteca Global e abre Reader interno',()=>{const h=read('public/index.html');const c=read('public/css/pdf-library.css');const u=read('public/js/pdf/pdf-library-ui.js');assert.match(h,/pdf-upload-layout/);assert.match(h,/Biblioteca Global/);assert.match(h,/pdfReaderOverlay/);assert.match(c,/\.pdf-upload-layout/);assert.match(u,/PdfStudyReader\.open/);assert.match(u,/Visualizar PDF/);});

test('Biblioteca mantém PDF visível quando a releitura remota falha',()=>{const c=read('public/js/pdf/pdf-core.js');const l=read('public/js/pdf/pdf-library.js');const u=read('public/js/pdf/pdf-library-ui.js');assert.match(c,/getSession\(\)/);assert.match(c,/isNetworkError/);assert.match(c,/async function retry/);assert.match(l,/CACHE_PREFIX/);assert.match(l,/rememberDocument/);assert.match(l,/__fromCache/);assert.match(u,/const uploaded=await global\.PdfStudyUpload\.upload/);assert.match(u,/state\.docs=\[uploaded/);assert.match(u,/upload concluído; sincronização de tela falhou/);});
