const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=r=>fs.readFileSync(path.join(root,r),'utf8');
test('Reader PDF interno está carregado e não usa visualizador temporário',()=>{const h=read('public/index.html'),u=read('public/js/pdf/pdf-library-ui.js');assert.match(h,/id="pdfReaderOverlay"/);assert.match(h,/vendor\/pdf\.min\.js/);assert.match(h,/pdf-reader\.js/);assert.match(u,/PdfStudyReader\.open/);});
test('Reader possui grifo sublinhado nota flashcard e exportação',()=>{const h=read('public/index.html'),r=read('public/js/pdf/pdf-reader.js');for(const s of ['Grifar','Sublinhar','Nota','Flashcard','Exportar para Anotações','Importar Anotações'])assert.match(h,new RegExp(s));assert.match(r,/saveAnnotation/);assert.match(r,/openFlashcardComposer/);assert.match(r,/createFlashcard/);assert.match(r,/exportToNotes/);assert.match(r,/importNotes/);});
test('anotações PDF têm RLS e versionamento',()=>{const s=read('supabase/migrations/20260819030000_create_pdf_reader_annotations.sql');assert.match(s,/create table if not exists public\.pdf_annotations/);assert.match(s,/enable row level security/);assert.match(s,/pdf_annotation_versions/);assert.match(s,/snapshot_pdf_annotation_version/);});
test('Reader possui navegaç��o por setas e roda do mouse',()=>{const h=read('public/index.html');const r=read('public/js/pdf/pdf-reader.js');assert.match(h,/Navegação/);assert.match(h,/moveVertical\(-1\)/);assert.match(h,/moveVertical\(1\)/);assert.match(r,/addEventListener\('wheel'/);assert.match(r,/ArrowUp/);assert.match(r,/ArrowDown/);assert.match(r,/ArrowLeft/);assert.match(r,/ArrowRight/);});
test('seleção aparece só quando há texto e flashcard sugere pergunta plausível',()=>{const r=read('public/js/pdf/pdf-reader.js');const h=read('public/index.html');assert.match(r,/if\(!g\)\{if\(state\.selected\)scheduleSelectionClear\(\);return\}/);assert.match(r,/inferQuestionFromSelection/);assert.match(h,/Pergunta sugerida automaticamente/);assert.match(r,/modalPdfFlashcard/);});
test('flashcard de trecho usa pergunta contextual sem fallback genérico',()=>{const r=read('public/js/pdf/pdf-reader.js');assert.doesNotMatch(r,/Qual distinção importante este trecho estabelece\?/);for(const token of ['Qual é a exceção indicada sobre','Quais requisitos o trecho aponta para','O que ocorre quando','Qual consequência jurídica recai sobre','Como o trecho diferencia'])assert.match(r,new RegExp(token));});
test('flashcard do PDF salva a partir do modal e abre o baralho do app',()=>{const r=read('public/js/pdf/pdf-reader.js'),u=read('public/js/app-ui.js');assert.match(r,/flashcardDraft=\{text:state\.selected\.text,page:state\.selected\.page/);assert.match(r,/const draft=flashcardDraft/);assert.doesNotMatch(r,/async function createFlashcard\(\)\{\s*if\(!state\.selected\)return alert\('Selecione um trecho do PDF primeiro\.'\)/);assert.match(r,/Flashcard salvo na área de Flashcards/);assert.match(r,/global\.openSearchFlashcardResult\?\.\(\{materia:draft\.materia,assunto:draft\.assunto\}\)/);assert.match(u,/function openSearchFlashcardResult\(fc\)/);assert.match(u,/setFlashcardViewFilter\(fc\.materia \|\| '', fc\.assunto \|\| ''\)/);});
test('botão de marcador de página comunica função e estado',()=>{const r=read('public/js/pdf/pdf-reader.js');assert.match(r,/setAttribute\('aria-pressed',active\?'true':'false'\)/);assert.match(r,/Remover marcador desta página/);assert.match(r,/Marcar esta página/);});
test('Biblioteca estabiliza loads concorrentes e concurso usa seletor atual',()=>{const u=read('public/js/pdf/pdf-library-ui.js');assert.match(u,/concursoSelect/);assert.match(u,/loadSeq/);assert.match(u,/seq!==state\.loadSeq/);});
test('upload modal tem limites responsivos e sem overflow horizontal',()=>{const c=read('public/css/pdf-library.css');assert.match(c,/max-height:calc\(100dvh - 28px\)/);assert.match(c,/overflow-x:hidden/);assert.match(c,/@media\(max-width:720px\)/);});


test('Reader renderiza página antes de bloquear em anota��ões e bookmarks',()=>{const r=read('public/js/pdf/pdf-reader.js');const renderPos=r.indexOf('await renderPage();setStatus(');const metadataPos=r.indexOf('const [annotations,bookmarks]=await Promise.all');assert.ok(renderPos>0);assert.ok(metadataPos>renderPos);});


test('Reader mobile suporta pinch customizado sem zoom da página e ajuste largura/página',()=>{const r=read('public/js/pdf/pdf-reader.js');const c=read('public/css/pdf-reader.css');const h=read('public/index.html');assert.match(r,/beginPinch/);assert.match(r,/movePinch/);assert.match(r,/endPinch/);assert.match(r,/touches\.length===2/);assert.match(r,/fitPage/);assert.match(r,/toggleFit/);assert.match(h,/pdfReaderFitButton/);assert.match(c,/touch-action:pan-x pan-y/);assert.match(c,/overscroll-behavior-x:none/);});

test('seleção mobile preserva snapshot ao tocar barra e geometria é normalizada por linhas',()=>{const r=read('public/js/pdf/pdf-reader.js');const c=read('public/css/pdf-reader.css');assert.match(r,/lockSelectionForAction/);assert.match(r,/scheduleSelectionClear/);assert.match(r,/normalizeRects/);assert.match(r,/range\.getClientRects\(\)/);assert.match(r,/selectionchange/);assert.match(c,/-webkit-user-select:text/);assert.match(c,/-webkit-touch-callout:default/);assert.match(c,/\.pdf-reader-selection-layer\{z-index:1/);assert.match(c,/\.pdf-reader-mark-layer\{z-index:2/);assert.match(c,/\.pdf-reader-text-layer\{z-index:3/);});

test('seleção do Reader usa feedback nativo fluido sem redesenho ou atrasos concorrentes',()=>{const r=read('public/js/pdf/pdf-reader.js');const c=read('public/css/pdf-reader.css');assert.match(r,/A seleção nativa permanece responsável pelo feedback visual/);assert.match(r,/const finishSelection=\(\)=>requestAnimationFrame\(updateSelection\)/);assert.doesNotMatch(r,/setTimeout\(updateSelection,/);assert.match(r,/nativeSelection&&!nativeSelection\.isCollapsed/);assert.match(c,/pdf-reader-text-layer ::selection\{background:rgba\(47,194,255,\.38\)/);assert.match(c,/pdf-reader-selection-layer\{z-index:1;pointer-events:none;display:none/);assert.match(c,/pdf-reader-text-layer\{touch-action:auto\}/);});


test('eventos globais de seleção são reativados a cada abertura do Reader',()=>{const r=read('public/js/pdf/pdf-reader.js');assert.match(r,/document\.removeEventListener\('selectionchange',onSelectionChange\)/);assert.match(r,/document\.addEventListener\('selectionchange',onSelectionChange\)/);assert.match(r,/wrap\.dataset\.bound!==['"]1['"]/);});
