-- V10.15.0 — Reader PDF interno: anotações, versões e marcadores privados.

create extension if not exists pgcrypto;

create table if not exists public.pdf_annotations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    pdf_id uuid not null references public.pdf_documents(id) on delete cascade,
    page_number integer not null check (page_number > 0),
    annotation_type text not null check (annotation_type in ('highlight','underline','note')),
    selected_text text,
    note_text text,
    color text not null default '#fde047',
    rects jsonb not null default '[]'::jsonb check (jsonb_typeof(rects) = 'array'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_pdf_annotations_user_pdf_page
    on public.pdf_annotations(user_id, pdf_id, page_number, created_at);

alter table public.pdf_annotations enable row level security;

drop policy if exists pdf_annotations_select_own on public.pdf_annotations;
create policy pdf_annotations_select_own on public.pdf_annotations
for select to authenticated using (auth.uid() = user_id);

drop policy if exists pdf_annotations_insert_own on public.pdf_annotations;
create policy pdf_annotations_insert_own on public.pdf_annotations
for insert to authenticated with check (
    auth.uid() = user_id
    and exists(select 1 from public.pdf_documents d where d.id = pdf_id and d.user_id = auth.uid())
);

drop policy if exists pdf_annotations_update_own on public.pdf_annotations;
create policy pdf_annotations_update_own on public.pdf_annotations
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists pdf_annotations_delete_own on public.pdf_annotations;
create policy pdf_annotations_delete_own on public.pdf_annotations
for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.pdf_annotation_versions (
    id bigint generated by default as identity primary key,
    annotation_id uuid not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    pdf_id uuid not null references public.pdf_documents(id) on delete cascade,
    page_number integer not null,
    annotation_type text not null,
    selected_text text,
    note_text text,
    color text,
    rects jsonb not null default '[]'::jsonb,
    version_number integer not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_pdf_annotation_versions_annotation
    on public.pdf_annotation_versions(user_id, annotation_id, version_number desc);

alter table public.pdf_annotation_versions enable row level security;
drop policy if exists pdf_annotation_versions_select_own on public.pdf_annotation_versions;
create policy pdf_annotation_versions_select_own on public.pdf_annotation_versions
for select to authenticated using (auth.uid() = user_id);

drop policy if exists pdf_annotation_versions_insert_own on public.pdf_annotation_versions;
create policy pdf_annotation_versions_insert_own on public.pdf_annotation_versions
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists pdf_annotation_versions_delete_own on public.pdf_annotation_versions;
create policy pdf_annotation_versions_delete_own on public.pdf_annotation_versions
for delete to authenticated using (auth.uid() = user_id);

create or replace function public.snapshot_pdf_annotation_version()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_next integer;
begin
  select coalesce(max(version_number),0)+1 into v_next
  from public.pdf_annotation_versions
  where annotation_id = old.id and user_id = old.user_id;

  insert into public.pdf_annotation_versions(
    annotation_id,user_id,pdf_id,page_number,annotation_type,selected_text,note_text,color,rects,version_number
  ) values (
    old.id,old.user_id,old.pdf_id,old.page_number,old.annotation_type,old.selected_text,old.note_text,old.color,old.rects,v_next
  );
  return new;
end;
$$;

drop trigger if exists trg_pdf_annotation_version on public.pdf_annotations;
create trigger trg_pdf_annotation_version
before update on public.pdf_annotations
for each row execute function public.snapshot_pdf_annotation_version();

create table if not exists public.pdf_bookmarks (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    pdf_id uuid not null references public.pdf_documents(id) on delete cascade,
    page_number integer not null check (page_number > 0),
    label text,
    created_at timestamptz not null default now(),
    unique(user_id,pdf_id,page_number)
);

alter table public.pdf_bookmarks enable row level security;
drop policy if exists pdf_bookmarks_select_own on public.pdf_bookmarks;
create policy pdf_bookmarks_select_own on public.pdf_bookmarks for select to authenticated using (auth.uid()=user_id);
drop policy if exists pdf_bookmarks_insert_own on public.pdf_bookmarks;
create policy pdf_bookmarks_insert_own on public.pdf_bookmarks for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists pdf_bookmarks_delete_own on public.pdf_bookmarks;
create policy pdf_bookmarks_delete_own on public.pdf_bookmarks for delete to authenticated using (auth.uid()=user_id);

-- Preserva o contrato JSONB da RPC existente e inclui as estruturas novas na limpeza total.
create or replace function public.delete_my_study_data()
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
    v_uid uuid := auth.uid();
    v_table text;
    v_count integer;
    v_result jsonb := '{}'::jsonb;
    v_tables constant text[] := array[
        'pdf_annotation_versions','pdf_annotations','pdf_bookmarks','pdf_document_links','pdf_progress','pdf_documents','study_workspaces',
        'edital','flashcards','user_flashcards','user_notes','user_schedules','user_settings'
    ];
begin
    if v_uid is null then raise exception 'Usuário não autenticado'; end if;
    foreach v_table in array v_tables loop
        if to_regclass(format('public.%I', v_table)) is not null then
            execute format('delete from public.%I where user_id = $1', v_table) using v_uid;
            get diagnostics v_count = row_count;
            v_result := v_result || jsonb_build_object(v_table, v_count);
        else
            v_result := v_result || jsonb_build_object(v_table, 0);
        end if;
    end loop;
    return v_result;
end;
$$;
revoke all on function public.delete_my_study_data() from public;
grant execute on function public.delete_my_study_data() to authenticated;

comment on table public.pdf_annotations is 'Marcações do Reader PDF: grifo, sublinhado e notas, persistidas por usuário/página.';
comment on table public.pdf_annotation_versions is 'Histórico de versões das anotações PDF.';
comment on table public.pdf_bookmarks is 'Marcadores de páginas do Reader PDF.';
